DROP TABLE IF EXISTS Departamentos;


CREATE TABLE [dbo].[Departamentos](
	[DepartamentoId] [int] NOT NULL,
	[Nombre] [nchar](100) NULL,
	PRIMARY KEY (DepartamentoId)

) ON [PRIMARY]
GO
/*!40000 ALTER TABLE `departamentos` DISABLE KEYS */;

INSERT INTO Departamentos (DepartamentoId, Nombre)
VALUES
	(5,'ANTIOQUIA'),
	(8,'ATLÁNTICO'),
	(11,'BOGOTÁ, D.C.'),
	(13,'BOLÍVAR'),
	(15,'BOYACÁ'),
	(17,'CALDAS'),
	(18,'CAQUETÁ'),
	(19,'CAUCA'),
	(20,'CESAR'),
	(23,'CÓRDOBA'),
	(25,'CUNDINAMARCA'),
	(27,'CHOCÓ'),
	(41,'HUILA'),
	(44,'LA GUAJIRA'),
	(47,'MAGDALENA'),
	(50,'META'),
	(52,'NARIÑO'),
	(54,'NORTE DE SANTANDER'),
	(63,'QUINDIO'),
	(66,'RISARALDA'),
	(68,'SANTANDER'),
	(70,'SUCRE'),
	(73,'TOLIMA'),
	(76,'VALLE DEL CAUCA'),
	(81,'ARAUCA'),
	(85,'CASANARE'),
	(86,'PUTUMAYO'),
	(88,'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA'),
	(91,'AMAZONAS'),
	(94,'GUAINÍA'),
	(95,'GUAVIARE'),
	(97,'VAUPÉS'),
	(99,'VICHADA');





/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;